In [1]:
import cv2
import numpy

In [2]:
im1=cv2.imread("C:/Users/CSES134/Pictures/blue.png")

In [3]:
im1

array([[[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]],

       [[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]],

       [[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]],

       ...,

       [[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]],

       [[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]],

       [[204,  72,  63],
        [204,  72,  63],
        [204,  72,  63],
        ...,
        [204,  72,  63],
        [204,  72,  63],
        [204,  72,  63]]

In [4]:
im2=cv2.imread("C:/Users/CSES134/Pictures/yellow.png")

In [5]:
im2

array([[[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]],

       [[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]],

       [[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]],

       ...,

       [[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]],

       [[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]],

       [[  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255],
        ...,
        [  0, 242, 255],
        [  0, 242, 255],
        [  0, 242, 255]]

In [6]:
cv2.imshow("img1",im1)
cv2.imshow("img2",im2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
im_blend=cv2.addWeighted(im1,0.5,im2,0.3,0)

In [8]:
cv2.imshow("im1",im1)
cv2.waitKey(0)
cv2.imshow("im2",im2)
cv2.waitKey(0)
cv2.imshow("Blended", im_blend)
cv2.waitKey(0)
cv2.destroyAllwindows()

AttributeError: module 'cv2' has no attribute 'destroyAllwindows'

# Colour Blending

In [9]:
import cv2
import numpy

In [10]:
im3=cv2.imread("C:/Users/CSES134/Pictures/im1.png")

In [11]:
im3

array([[[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]],

       [[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]],

       [[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]],

       ...,

       [[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]],

       [[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]],

       [[231, 191, 200],
        [231, 191, 200],
        [231, 191, 200],
        ...,
        [231, 191, 200],
        [231, 191, 200],
        [231, 191, 200]]

In [12]:
im4=cv2.imread("C:/Users/CSES134/Pictures/im2.png")

In [13]:
im4

array([[[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]],

       [[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]],

       [[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]],

       ...,

       [[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]],

       [[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]],

       [[ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136],
        ...,
        [ 21,   0, 136],
        [ 21,   0, 136],
        [ 21,   0, 136]]

In [14]:
cv2.imshow("img3",im3)
cv2.imshow("img4",im4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
blend=cv2.addWeighted(im3,0.5,im4,0.3,0)

In [16]:
cv2.imshow("blended img",blend)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
sub=cv2.subtract(im3,im4)

In [18]:
cv2.imshow("sub",sub)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
And=cv2.bitwise_and(im3,im4)
OR=cv2.bitwise_or(im3,im4)
NOT=cv2.bitwise_not(im3,im4)
XOR=cv2.bitwise_xor(im3,im4)

In [20]:
cv2.imshow("and",And)
cv2.waitKey(0)
cv2.imshow("or",OR)
cv2.waitKey(0)
cv2.imshow("not",NOT)
cv2.waitKey(0)
cv2.imshow("xor",XOR)
cv2.waitKey(0)

-1

# ROI-Region Of Interest

In [21]:
im5=cv2.imread("C:/Users/CSES134/Pictures/nature.jpg")

In [22]:
roi=im5[0:50,]

In [23]:
cv2.imshow("r",roi)
cv2.waitKey(0)
cv2.destroyAllWindows()