In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
im1=cv2.imread("climb.jpg",0)

In [4]:
im1

array([[ 39,  41,  44, ..., 109, 106, 104],
       [ 39,  40,  43, ..., 109, 107, 105],
       [ 39,  40,  42, ..., 108, 107, 106],
       ...,
       [ 76,  83,  80, ...,  17,  18,  15],
       [ 73,  79,  76, ...,  20,  19,  15],
       [ 68,  74,  71, ...,  22,  20,  15]], dtype=uint8)

In [5]:
shp=im1.shape 
print(shp)

(348, 612)


In [6]:
height,width=im1.shape[:2]
print(height)
print(width)

348
612


In [7]:
cent=(height/2,width/2)
cent

(174.0, 306.0)

In [8]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=30,scale=0.6)

In [9]:
print(rotation_matrix)

[[  0.51961524   0.3         -8.21305216]
 [ -0.3          0.51961524 199.19773587]]


In [10]:
rotated_im=cv2.warpAffine(src=im1, M=rotation_matrix, dsize=(width, height))

In [11]:
cv2.imshow("Original image", im1)
cv2.waitKey(0)
cv2.imshow("Rotated image", rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Translation Matrix

In [12]:
tx,ty=width/2,height/2

In [13]:
ty

174.0

In [14]:
Translation_matrix=np.array([[1,0,tx],[0,1,ty]])

In [15]:
Translation_matrix

array([[  1.,   0., 306.],
       [  0.,   1., 174.]])

In [19]:
Trans_im=cv2.warpAffine(src=im1,M=Translation_matrix,dsize=(height,width))

In [20]:
cv2.imshow("Original image", im1)
cv2.waitKey(0)
cv2.imshow("Trans image", Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()