# K-MEANS CLUSTERING

In [1]:
import cv2
import numpy as np

# READING IMAGE

In [2]:
img=cv2.imread("climb.jpg")
img

array([[[ 28,  37,  47],
        [ 30,  38,  51],
        [ 33,  40,  55],
        ...,
        [ 82, 102, 133],
        [ 79,  99, 130],
        [ 77,  97, 128]],

       [[ 30,  36,  47],
        [ 31,  37,  50],
        [ 32,  39,  54],
        ...,
        [ 82, 103, 131],
        [ 80, 101, 129],
        [ 78,  99, 127]],

       [[ 32,  36,  47],
        [ 33,  36,  50],
        [ 33,  38,  53],
        ...,
        [ 81, 102, 130],
        [ 80, 101, 129],
        [ 79, 100, 128]],

       ...,

       [[ 42,  68, 104],
        [ 51,  71, 118],
        [ 48,  67, 118],
        ...,
        [ 13,  17,  18],
        [ 14,  18,  19],
        [ 11,  15,  16]],

       [[ 41,  65, 101],
        [ 47,  68, 113],
        [ 46,  63, 114],
        ...,
        [ 16,  20,  21],
        [ 15,  19,  20],
        [ 11,  15,  16]],

       [[ 38,  60,  95],
        [ 44,  63, 106],
        [ 43,  58, 107],
        ...,
        [ 18,  22,  23],
        [ 16,  20,  21],
        [ 11,  15,  16]]

# RGB CONVERSION

In [4]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# RESHAPE

In [5]:
vec=imgrgb.reshape((-1,3))
vec

array([[47, 37, 28],
       [51, 38, 30],
       [55, 40, 33],
       ...,
       [23, 22, 18],
       [21, 20, 16],
       [16, 15, 11]], dtype=uint8)

# FLOAT CONVERSION

In [7]:
vec=np.float32(vec)
vec

array([[47., 37., 28.],
       [51., 38., 30.],
       [55., 40., 33.],
       ...,
       [23., 22., 18.],
       [21., 20., 16.],
       [16., 15., 11.]], dtype=float32)

# ITERATION TERMINATION CRITERIA

In [8]:
criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 1)

In [9]:
criteria

(3, 100, 1)

# CLUSTER CONDITIONS

In [10]:
k=3
attempts=100

# K-MEANS

In [11]:
compactness,label,center=cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[204.21313 , 156.77446 , 110.68391 ],
       [ 44.77256 ,  33.43882 ,  25.47575 ],
       [120.90649 ,  83.041504,  54.467266]], dtype=float32)

In [12]:
compactness

346095871.51373696

In [13]:
label

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int32)

# UINT CONVERSION

In [14]:
center = np.uint8(center)
center

array([[204, 156, 110],
       [ 44,  33,  25],
       [120,  83,  54]], dtype=uint8)

# FLATTENING AND RESHAPE

In [15]:
res=center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25],
        ...,
        [120,  83,  54],
        [120,  83,  54],
        [120,  83,  54]],

       [[ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25],
        ...,
        [120,  83,  54],
        [120,  83,  54],
        [120,  83,  54]],

       [[ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25],
        ...,
        [120,  83,  54],
        [120,  83,  54],
        [120,  83,  54]],

       ...,

       [[120,  83,  54],
        [120,  83,  54],
        [120,  83,  54],
        ...,
        [ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25]],

       [[120,  83,  54],
        [120,  83,  54],
        [120,  83,  54],
        ...,
        [ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25]],

       [[120,  83,  54],
        [120,  83,  54],
        [120,  83,  54],
        ...,
        [ 44,  33,  25],
        [ 44,  33,  25],
        [ 44,  33,  25]]

# IMAGE

In [16]:
cv2.imshow('original',img)
cv2.imshow('segmented',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
image =cv2.imread('climb.jpg')
segmented_image=cv2.pyrMeanShiftFiltering(image,40,40)
cv2.imshow('original_Image',image)
cv2.imshow('Segmented Image',segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()